### ISSUE TITLE
unpublish?

### ISSUE THREAD

**Issue by jonschlinkert** [PatrickJS/gulp-copyright#1]
Looks like you never got around to publishing this. Would you mind unpublishing from npm so it can be used? I'd like to create a plugin for [update-copyright](https://github.com/jonschlinkert/update-copyright). Thanks in advance

**Comment by PatrickJS** [comment]
npm doesn't allow unpublishing anymore. I can add you to the repo and npm

**Comment by jonschlinkert** [comment]
no thanks
